-- Script generated by Lokasenna's GUI Builder


local lib_path = reaper.GetExtState("Lokasenna_GUI", "lib_path_v2")
if not lib_path or lib_path == "" then
    reaper.MB("Couldn't load the Lokasenna_GUI library. Please run 'Set Lokasenna_GUI v2 library path.lua' in the Lokasenna_GUI folder.", "Whoops!", 0)
    return
end
loadfile(lib_path .. "Core.lua")()




GUI.req("Classes/Class - Textbox.lua")()
GUI.req("Classes/Class - Button.lua")()
-- If any of the requested libraries weren't found, abort the script.
if missing_lib then return 0 end



GUI.name = "New script GUI"
GUI.x, GUI.y, GUI.w, GUI.h = 0, 0, 640, 480
GUI.anchor, GUI.corner = "mouse", "C"



GUI.New("seq3", "Textbox", {
    z = 11,
    x = 48,
    y = 112,
    w = 148,
    h = 20,
    caption = "seq3",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})

GUI.New("seq4", "Textbox", {
    z = 11,
    x = 48,
    y = 144,
    w = 148,
    h = 20,
    caption = "seq4",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})

GUI.New("seq7", "Textbox", {
    z = 11,
    x = 48,
    y = 240,
    w = 148,
    h = 20,
    caption = "seq7",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})

GUI.New("seq8", "Textbox", {
    z = 11,
    x = 48,
    y = 272,
    w = 148,
    h = 20,
    caption = "seq8",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})

GUI.New("make", "Button", {
    z = 11,
    x = 48,
    y = 304,
    w = 48,
    h = 24,
    caption = "make",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame"
})

GUI.New("seq5", "Textbox", {
    z = 11,
    x = 48,
    y = 176,
    w = 148,
    h = 20,
    caption = "seq5",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})

GUI.New("seq6", "Textbox", {
    z = 11,
    x = 48,
    y = 208,
    w = 148,
    h = 20,
    caption = "seq6",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})

GUI.New("seq1", "Textbox", {
    z = 11,
    x = 48,
    y = 48,
    w = 148,
    h = 20,
    caption = "seq1",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})

GUI.New("origin", "Textbox", {
    z = 11,
    x = 48,
    y = 16,
    w = 148,
    h = 20,
    caption = "origin",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})

GUI.New("seq2", "Textbox", {
    z = 11,
    x = 48,
    y = 80,
    w = 148,
    h = 20,
    caption = "seq2",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})







GUI.Init()
GUI.Main()
